# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: banque.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'banque.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62\x61nque.proto\x12\x16\x63om.master.banque.grpc\":\n\rClientRequest\x12\x12\n\nnumero_tel\x18\x01 \x01(\t\x12\x15\n\rsolde_initial\x18\x02 \x01(\x03\"[\n\x0e\x43lientResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nnumero_tel\x18\x03 \x01(\t\x12\x14\n\x0csolde_actuel\x18\x04 \x01(\x03\"\"\n\x0cSoldeRequest\x12\x12\n\nnumero_tel\x18\x01 \x01(\t\"M\n\rSoldeResponse\x12\x12\n\nnumero_tel\x18\x01 \x01(\t\x12\r\n\x05solde\x18\x02 \x01(\x03\x12\x19\n\x11\x64\x61te_consultation\x18\x03 \x01(\t\"K\n\x10TransfertRequest\x12\x10\n\x08\x65metteur\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x65stinataire\x18\x02 \x01(\t\x12\x0f\n\x07montant\x18\x03 \x01(\x03\"g\n\x11TransfertResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\treference\x18\x03 \x01(\t\x12\x1e\n\x16nouveau_solde_emetteur\x18\x04 \x01(\x03\"=\n\rStreamRequest\x12\x12\n\nnumero_tel\x18\x01 \x01(\t\x12\x18\n\x10max_transactions\x18\x02 \x01(\x05\"[\n\x0bTransaction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07montant\x18\x03 \x01(\x03\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t2\x9b\x03\n\rBanqueService\x12\\\n\x0b\x43reerClient\x12%.com.master.banque.grpc.ClientRequest\x1a&.com.master.banque.grpc.ClientResponse\x12]\n\x0e\x43onsulterSolde\x12$.com.master.banque.grpc.SoldeRequest\x1a%.com.master.banque.grpc.SoldeResponse\x12i\n\x12\x45\x66\x66\x65\x63tuerTransfert\x12(.com.master.banque.grpc.TransfertRequest\x1a).com.master.banque.grpc.TransfertResponse\x12\x62\n\x12StreamTransactions\x12%.com.master.banque.grpc.StreamRequest\x1a#.com.master.banque.grpc.Transaction0\x01\x42\'\n\x16\x63om.master.banque.grpcB\x0b\x42\x61nqueProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banque_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.master.banque.grpcB\013BanqueProtoP\001'
  _globals['_CLIENTREQUEST']._serialized_start=40
  _globals['_CLIENTREQUEST']._serialized_end=98
  _globals['_CLIENTRESPONSE']._serialized_start=100
  _globals['_CLIENTRESPONSE']._serialized_end=191
  _globals['_SOLDEREQUEST']._serialized_start=193
  _globals['_SOLDEREQUEST']._serialized_end=227
  _globals['_SOLDERESPONSE']._serialized_start=229
  _globals['_SOLDERESPONSE']._serialized_end=306
  _globals['_TRANSFERTREQUEST']._serialized_start=308
  _globals['_TRANSFERTREQUEST']._serialized_end=383
  _globals['_TRANSFERTRESPONSE']._serialized_start=385
  _globals['_TRANSFERTRESPONSE']._serialized_end=488
  _globals['_STREAMREQUEST']._serialized_start=490
  _globals['_STREAMREQUEST']._serialized_end=551
  _globals['_TRANSACTION']._serialized_start=553
  _globals['_TRANSACTION']._serialized_end=644
  _globals['_BANQUESERVICE']._serialized_start=647
  _globals['_BANQUESERVICE']._serialized_end=1058
# @@protoc_insertion_point(module_scope)
