# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import banque_pb2 as banque__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in banque_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BanqueServiceStub(object):
    """Service de gestion bancaire
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreerClient = channel.unary_unary(
                '/com.master.banque.grpc.BanqueService/CreerClient',
                request_serializer=banque__pb2.ClientRequest.SerializeToString,
                response_deserializer=banque__pb2.ClientResponse.FromString,
                _registered_method=True)
        self.ConsulterSolde = channel.unary_unary(
                '/com.master.banque.grpc.BanqueService/ConsulterSolde',
                request_serializer=banque__pb2.SoldeRequest.SerializeToString,
                response_deserializer=banque__pb2.SoldeResponse.FromString,
                _registered_method=True)
        self.EffectuerTransfert = channel.unary_unary(
                '/com.master.banque.grpc.BanqueService/EffectuerTransfert',
                request_serializer=banque__pb2.TransfertRequest.SerializeToString,
                response_deserializer=banque__pb2.TransfertResponse.FromString,
                _registered_method=True)
        self.StreamTransactions = channel.unary_stream(
                '/com.master.banque.grpc.BanqueService/StreamTransactions',
                request_serializer=banque__pb2.StreamRequest.SerializeToString,
                response_deserializer=banque__pb2.Transaction.FromString,
                _registered_method=True)


class BanqueServiceServicer(object):
    """Service de gestion bancaire
    """

    def CreerClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsulterSolde(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EffectuerTransfert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTransactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BanqueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreerClient': grpc.unary_unary_rpc_method_handler(
                    servicer.CreerClient,
                    request_deserializer=banque__pb2.ClientRequest.FromString,
                    response_serializer=banque__pb2.ClientResponse.SerializeToString,
            ),
            'ConsulterSolde': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsulterSolde,
                    request_deserializer=banque__pb2.SoldeRequest.FromString,
                    response_serializer=banque__pb2.SoldeResponse.SerializeToString,
            ),
            'EffectuerTransfert': grpc.unary_unary_rpc_method_handler(
                    servicer.EffectuerTransfert,
                    request_deserializer=banque__pb2.TransfertRequest.FromString,
                    response_serializer=banque__pb2.TransfertResponse.SerializeToString,
            ),
            'StreamTransactions': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTransactions,
                    request_deserializer=banque__pb2.StreamRequest.FromString,
                    response_serializer=banque__pb2.Transaction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.master.banque.grpc.BanqueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.master.banque.grpc.BanqueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BanqueService(object):
    """Service de gestion bancaire
    """

    @staticmethod
    def CreerClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.master.banque.grpc.BanqueService/CreerClient',
            banque__pb2.ClientRequest.SerializeToString,
            banque__pb2.ClientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsulterSolde(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.master.banque.grpc.BanqueService/ConsulterSolde',
            banque__pb2.SoldeRequest.SerializeToString,
            banque__pb2.SoldeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EffectuerTransfert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.master.banque.grpc.BanqueService/EffectuerTransfert',
            banque__pb2.TransfertRequest.SerializeToString,
            banque__pb2.TransfertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.master.banque.grpc.BanqueService/StreamTransactions',
            banque__pb2.StreamRequest.SerializeToString,
            banque__pb2.Transaction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
